---

- name: "Rust | Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 600
  become: true
  become_user: root

- name: "Rust | Install dependencies"
  apt:
    name:
      - curl
      - gcc
    state: present
  become: true
  become_user: root
